### ISSUE TITLE
README.md --> skills section can be improved

### ISSUE THREAD

**Issue by AldrinSeanPereira** [VishwaS-22/VishwaS-22#2]
Hi Vishwa,

The skills section in your README.md has skills rated out of 5 which is actually not a good representation of your skills.
One way to fix this is to simply list out your skills instead. Or you could refer this article as a start --> [Reference here](https://www.careers.govt.nz/job-hunting/cvs-and-cover-letters/how-to-describe-skills-in-your-cv/)

Looking forward to all the improvements you can further make on your profile :)

**Comment by VishwaS-22** [comment]
Hey @AldrinSeanPereira! Thanks for the suggestion man. Now I fixed it.
